data:
  eval_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/crawl/eval_en_00_of_18.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/crawl_2/train_en_00_of_18.jsonl
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/baselines/icae/
llm_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
llm_type: mistral
embedder_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
embed_type: mistral
num_microbatches: 1
seed: 0
max_steps: 200000
seq_len: 512
log_freq: 10
batch_size: 32
ckpt_freq: 5000
eval_freq: 50
no_eval: false
continuation: 0.5
max_norm: 2.0
optim:
  type: linear
  final_lr: 1.0e-20
  initial_lr: 1.0e-20
  max_lr: 0.0001
  warm_up_steps: 300
  weight_decay: 0.0
lora_embedder:
  enable: true
  rank: 128
  scaling: 2.0
lora_llm:
  enable: false
  rank: 128
  scaling: 2.0
pipeline:
  embedder_params:
    causal_embedder: true
    n_truncated_layers: 0
    pooling_module:
      pool_type: mean
      where: between
    trained_layers: 0
    train_embedding_mtx: false
    memory_tokens: 64
    rec_tok: true
    cont_tok: true
  max_embeds: 1
  trainable_llm: false
  w_embeds: true
num_ckpt_keep: 2
exp_name: icae_64memtoks_mistral
wandb:
  key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
  offline: false
  project: embed_llm
  run_name: icae_64memtoks_mistral
