data:
  eval_data: eval_ReadComp/squad_test.jsonl
  adapt_seq_len: true
  prefix: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/
  train_data: synthesized/final_specified_datasets/pisco_fs_split/adversarial_qa.jsonl:29967.0:3,synthesized/final_specified_datasets/pisco_fs_split/asqa.jsonl:4353.0:3,synthesized/final_specified_datasets/pisco_fs_split/freebase_qa.jsonl:20355.0:3,synthesized/final_specified_datasets/pisco_fs_split/hotpotqa.jsonl:88833.0:3,synthesized/final_specified_datasets/pisco_fs_split/msmarco.jsonl:59695.0:3,synthesized/final_specified_datasets/pisco_fs_split/nq_open.jsonl:87923.0:3,synthesized/final_specified_datasets/pisco_fs_split/sciq.jsonl:11679.0:3,synthesized/final_specified_datasets/pisco_fs_split/squad.jsonl:87594.0:3,synthesized/final_specified_datasets/pisco_fs_split/triviaqa.jsonl:61796.0:3,synthesized/final_specified_datasets/pisco_fs_split/wikiqa.jsonl:813.0:3
  sep_passages: true
  n_interleaved: 2
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/baselines/pisco/
llm_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/Llama3.1-8B
llm_type: llama
embedder_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/Llama3.1-8B
embed_type: llama
num_microbatches: 1
seed: 0
max_steps: 3600
seq_len: 128
log_freq: 10
batch_size: 16
ckpt_freq: 1000
eval_freq: 50
no_eval: false
continuation: 0.0
max_norm: 1.0
optim:
  type: linear
  final_lr: 1.0e-20
  initial_lr: 1.0e-20
  max_lr: 0.0001
  warm_up_steps: 177
  weight_decay: 0.1
lora_embedder:
  enable: true
  rank: 16
  scaling: 2.0
lora_llm:
  enable: true
  rank: 16
  scaling: 2.0
pipeline:
  embedder_params:
    causal_embedder: true
    n_truncated_layers: 0
    pooling_module:
      pool_type: mean
      where: between
    trained_layers: 32
    train_embedding_mtx: false
    memory_tokens: 16
    cont_tok: true
  max_embeds: -5
  trainable_llm: true
  w_embeds: true
num_ckpt_keep: 2
exp_name: Pisco_16memtoks_llama_v2
wandb:
  key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
  offline: false
  project: embed_llm
  run_name: Pisco_16memtoks_llama_v2
