model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
llm_name: Mistral7B
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/
exp_name: test_pretrain
continuation: false
textual_continuation: 0.0
lora:
  rank: 64
  scaling: 2.0
  enable: true
pipeline:
  w_embeds: true
  embedder_name: NVEmbed
  trainable_embedder: false
  n_truncated_layers: 8
  do_pool: true
  cross_att: true
  cross_att_layers: 16
  mlp_project:
    hidden_dim: 4096
    n_layers: 1
    act: gelu
    type: mlp
  do_both: true
  shared_kv: false
  every_cross_att: null
  pooled_cross_att: false
  prefix_prompt: false
  trainable_llm: true
  train_only_pooling: false
  gate_bottleneck: 8
data:
  eval_data: /lustre/scwpod02/client/kyutai-interns/datasets/crawl_2/train_en_00_of_18.jsonl
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/crawl_2/train_en_00_of_18.jsonl
  shuffle: false
  adapt_seq_len: true
optim:
  max_lr: 5.0e-05
  weight_decay: 0.1
  warm_up_steps: 5
  initial_lr: 1.0e-20
  final_lr: 1.0e-10
hybrid_task:
  do: true
  max_n_prefixes: 1
  min_n_prefixes: 0
  prop_continuation: 0.0
  prop_noembed_continuation: 0.5
  prop_uselessembed_continuation: 0.0
  one_task_4_all: true
  max_embeds: 2

seq_len: 256
batch_size: 32
num_microbatches: 1
max_steps: 40
seed: 0
log_freq: 1
eval_freq: 1
no_eval: true
ckpt_freq: 500
save_adapters: true


# wandb:
#   project: embed_llm
#   run_name: pretrain_both_trained_07_singpassage_0f6f2a1a
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false



