batch_size: 1
ckpt_freq: 2
data:
  eval_data: /lustre/scwpod02/client/kyutai-interns/datasets/modular_finetuning/enwiki-20220120_valid.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/modular_finetuning/enwiki-20220120_train.jsonl
eval_freq: 100
exp_name: test
llm_name: Mistral7B
log_freq: 10
lora:
  enable: true
  rank: 64
  scaling: 2.0
max_steps: 20000
model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
no_eval: false
num_microbatches: 1
optim:
  final_lr: 1.0e-10
  initial_lr: 1.0e-20
  max_lr: 5.0e-05
  warm_up_steps: 500
  weight_decay: 0.1
pipeline:
  w_embeds: true
  norm_wo_embeds: false
  embedder_name: Mistral7B
  trainable_embedder: true
  n_truncated_layers: 8
  normalize_embeddings: true
  continuation: false
  causal: false
  do_pool: true
  cross_att: true
  cross_att_layers: null
  mlp_project:
    hidden_dim: 4096
    n_layers: 3
    act: gelu
    type: reversed_latent_attention
  pooling_module:
    type: reversed_latent_attention
    r: 512
    n_heads: 8
  do_both: true
  shared_kv: false
  every_cross_att: 2
  pooled_cross_att: true
  dist_process: false
  mlm: false
  trainable_llm: false

run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/
save_adapters: true
seed: 0
seq_len: 256
# wandb:
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false
#   project: embed_llm
#   run_name: 128_SL_FN_Truemean_0_MLP_8_TRUNC_True_CA_16_CAL_False_SKV_False_DB_new_pooled_cross_att
