model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
llm_name: Mistral7B
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/
exp_name: test
lora:
  rank: 64
  scaling: 2.0
  enable: true
pipeline:
  w_embeds: true
  norm_wo_embeds: false
  embedder_name: NVEmbed
  trainable_embedder: false
  n_truncated_layers: 4
  normalize_embeddings: true
  continuation: false
  do_pool: true
  cross_att: true
  cross_att_layers: 5
  mlp_project:
    hidden_dim: 4096
    n_layers: 0
    act: gelu
  shared_kv: true
data:
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/modular_finetuning/enwiki-20220120_train.jsonl
  eval_data: /lustre/scwpod02/client/kyutai-interns/datasets/modular_finetuning/enwiki-20220120_valid.jsonl
  shuffle: false
seq_len: 512
batch_size: 32
num_microbatches: 1
max_steps: 10000
optim:
  max_lr: 5.0e-05
  weight_decay: 0.1
  warm_up_steps: 500
  initial_lr: 1.0e-20
  final_lr: 1.0e-10
seed: 0
log_freq: 10
eval_freq: 100
no_eval: true
ckpt_freq: 500
save_adapters: true
# wandb:
#   project: embed_llm
#   run_name: test
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false

