# Llama3.1-8B  Llama3.2-3B
embedder_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
llm_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
llm_type: mistral
embed_type: mistral
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/
exp_name: test_pretrain2

data:
  eval_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/crawl/eval_en_00_of_18.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/crawl_2/train_en_00_of_18.jsonl
  n_interleaved: 3

continuation: 0.8

no_eval: false
num_microbatches: 1

optim:
  final_lr: 1.0e-10
  initial_lr: 1.0e-20
  max_lr: 5.0e-7
  warm_up_steps: 3
  weight_decay: 0.1
  max_lr_projector: 5.0e-5


pipeline:
  embedder_params:
    causal_embedder: true
    compress_rates:
    - -8
    n_truncated_layers: 14
    pooling_module:
      pool_type: mean_sa
      where: before
    trained_layers: 14
    train_embedding_mtx: true
    rec_tok: true
    cont_tok: true
  max_embeds: 1
  trainable_llm: false
  w_embeds: true
  w_prefix_prompt: false
  bridge_module:
    bridge_type: mlp
    in_dim: 4096
    hidden_dim: 2048
    out_dim: 4096

data:
  adapt_seq_len: false
  eval_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/crawl/eval_en_00_of_18.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/crawl_2/train_en_00_of_18.jsonl
  n_interleaved: 3 
  loss_last_cont_only: true


seq_len: 1792
batch_size: 16
num_microbatches: 1
max_steps: 10000


seed: 0
log_freq: 1
eval_freq: 50
no_eval: true
ckpt_freq: 10

# from_ckpt:
#   do: True
#   decoder_path: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/4P_TruncL_16_TrainL_4_decL16_newinit/checkpoints/checkpoint_010000/llm/decoder/consolidated
#   embedder_path: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/4P_TruncL_16_TrainL_4_decL16_newinit/checkpoints/checkpoint_010000/


# wandb:
#   project: embed_llm
#   run_name: pretrain_both_trained_07_singpassage_0f6f2a1a
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false




