model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
llm_name: Mistral7B
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/
exp_name: test_pretrain


lora:
  enable: false
  rank: 128
  scaling: 2.0
  
model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
no_eval: false
num_microbatches: 1
optim:
  final_lr: 1.0e-10
  initial_lr: 1.0e-20
  max_lr: 5.0e-05
  warm_up_steps: 500
  weight_decay: 0.1
pipeline:
  causal_embedder: true
  cross_att: false
  cross_att_layers: null
  do_both: false
  do_pool: true
  embedder_name: Mistral7B
  every_cross_att: 2
  gate_bottleneck: 8
  max_embeds: 2
  mlp_project:
    act: gelu
    hidden_dim: 4096
    n_layers: 1
    type: mlp
  n_truncated_layers: 31
  pooled_cross_att: false
  pooling_module:
    compress_rate: -1
    type: adaptive_attention
    pool_type: mean_sa
    rms_norm: false
  normalize_embed: false
  shared_kv: false
  train_only_pooling: true
  trainable_embedder: false
  trainable_llm: false
  w_embeds: true
  w_prefix_prompt: false
  insert_layer: 8



data:
  adapt_seq_len: false
  eval_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/crawl/eval_en_00_of_18.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/crawl_2/train_en_00_of_18.jsonl
  prob_distractor: 0.5

seq_len: 256
batch_size: 16
num_microbatches: 1
max_steps: 50
optim:
  max_lr: 5.0e-05
  weight_decay: 0.1
  warm_up_steps: 2
  initial_lr: 1.0e-20
  final_lr: 1.0e-10

seed: 0
log_freq: 1
eval_freq: 1
no_eval: true
ckpt_freq: 10
save_adapters: true


# wandb:
#   project: embed_llm
#   run_name: pretrain_both_trained_07_singpassage_0f6f2a1a
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false




