data:
  eval_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/crawl/eval_en_00_of_18.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/crawl_2/train_en_00_of_18.jsonl
  n_interleaved: 3
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/
llm_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
llm_type: mistral
embedder_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/Llama3.2-3B
embed_type: llama
num_microbatches: 1
seed: 0
max_steps: 30000
seq_len: 1792
log_freq: 1
batch_size: 16
ckpt_freq: 5000
eval_freq: 50
no_eval: true
continuation: 0.9
optim:
  final_lr: 1.0e-10
  initial_lr: 1.0e-20
  max_lr: 1.0e-05
  max_lr_projector: 5.0e-05
  warm_up_steps: 1000
  weight_decay: 0.1
pipeline:
  embedder_params:
    causal_embedder: true
    compress_rates:
    - -8
    n_truncated_layers: 14
    pooling_module:
      pool_type: mean_sa
      where: before
    trained_layers: 14
    train_embedding_mtx: true
    rec_tok: true
    cont_tok: true
  max_embeds: 1
  trainable_llm: false
  w_embeds: true
  w_prefix_prompt: false
  bridge_module:
    bridge_type: mlp
    in_dim: 3072
    hidden_dim: 2048
    out_dim: 4096
num_ckpt_keep: 4
exp_name: test_pretrain2
# wandb:
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false
#   project: embed_llm
#   run_name: CPtrue16_L3B_MLP2_M7B_5rec
