model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/
exp_name: test_pretrain


continuation: 0.8
textual_continuation: 0.0

lora_llm:
  enable: false
  rank: 128
  scaling: 2.0

lora_embedder:
  enable: false
  rank: 128
  scaling: 2.0

model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
no_eval: false
num_microbatches: 1

optim:
  final_lr: 1.0e-10
  initial_lr: 1.0e-20
  max_lr: 5.0e-05
  warm_up_steps: 500
  weight_decay: 0.1

pipeline:
  embedder_params:
    causal_embedder: true
    compress_rates:
    - -16
    n_truncated_layers: 16
    pooling_module:
      pool_type: mean_sa
      where: before
    trained_layers: 4
    rec_tok: true
    mixed_method: true
    memory_tokens: 128
  max_embeds: 1
  trainable_llm: false
  w_embeds: true
  w_prefix_prompt: false
  decoder_module:
    do: true
    n_layers: 1
    insert_at: 16



data:
  adapt_seq_len: false
  eval_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/crawl/eval_en_00_of_18.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/crawl_2/train_en_00_of_18.jsonl


seq_len: 256
batch_size: 16
num_microbatches: 1
max_steps: 10000


seed: 0
log_freq: 1
eval_freq: 50
no_eval: true
ckpt_freq: 10

# from_ckpt:
#   do: True
#   decoder_path: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/4P_TruncL_16_TrainL_4_decL16_newinit/checkpoints/checkpoint_010000/llm/decoder/consolidated
#   embedder_path: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/4P_TruncL_16_TrainL_4_decL16_newinit/checkpoints/checkpoint_010000/


# wandb:
#   project: embed_llm
#   run_name: pretrain_both_trained_07_singpassage_0f6f2a1a
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false




