model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
llm_name: Mistral7B
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/
exp_name: test_decompress

lora:
  rank: 64
  scaling: 2.0
  enable: true

start_from_ckpt_path: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/ToyPretraining_LLM_False_Emb_True_MaxEmb_1_pure_reconstruct_16BS/checkpoints/checkpoint_030000
continuation: false

toy_tests:
  do: true
  kl_pretraining: false
  alpha: 1.0
  tune_llm: true
  tune_embedder: false
  decompress_usage: 'reversed'

data:
  adapt_seq_len: false
  eval_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/crawl/eval_en_00_of_18.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/crawl_2/train_en_00_of_18.jsonl

seq_len: 256
batch_size: 32
num_microbatches: 1
max_steps: 30000
optim:
  max_lr: 5.0e-05
  weight_decay: 0.1
  warm_up_steps: 500
  initial_lr: 1.0e-20
  final_lr: 1.0e-10

seed: 0
log_freq: 1
eval_freq: 1
no_eval: false
ckpt_freq: 500
save_adapters: true


# wandb:
#   project: embed_llm
#   run_name: pretrain_both_trained_07_singpassage_0f6f2a1a
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false




