batch_size: 16
ckpt_freq: 10
data:
  eval_data: /lustre/scwpod02/client/kyutai-interns/datasets/modular_finetuning/enwiki-20220120_valid.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/modular_finetuning/enwiki-20220120_train.jsonl
embedder:
  dim: 4096
  name: NVEmbed
eval_freq: 50
exp_name: debug_mistral3
llm_name: Mistral7B
log_freq: 1
lora:
  enable: true
  rank: 64
  scaling: 2.0
max_steps: 1000
model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
no_eval: false
norm_wo_embeds: false
optim:
  final_lr: 1.0e-10
  initial_lr: 1.0e-20
  max_lr: 5.0e-06
  pct_start: 0.2
  weight_decay: 0.1
projector:
  act: id
  hidden_dim: 4096
  n_layers: 2
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/
save_adapters: true
seed: 0
seq_len: 512
w_embeds: true
# wandb:
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false
#   project: embed_llm
#   run_name: mlp_proj7a3a4ade9c98ec81b556
