model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
llm_name: Mistral7B
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/
exp_name: test
lora:
  rank: 64
  scaling: 2.0
  enable: true
pipeline:
  w_embeds: true
  norm_wo_embeds: false
  embedder_name: NVEmbed
  trainable_embedder: false
  n_truncated_layers: 8
  normalize_embeddings: true
  continuation: false
  do_pool: true
  cross_att: true
  cross_att_layers: null
  mlp_project:
    hidden_dim: 4096
    n_layers: 1
    act: gelu
    type: latent_attention
  do_both: true
  shared_kv: false
  every_cross_att: 2
  pooled_cross_att: true
  dist_process: false
data:
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/modular_finetuning/enwiki-20220120_train.jsonl
  eval_data: /lustre/scwpod02/client/kyutai-interns/datasets/modular_finetuning/enwiki-20220120_valid.jsonl
  shuffle: false
seq_len: 128
batch_size: 32
num_microbatches: 1
max_steps: 20000
optim:
  max_lr: 5.0e-05
  weight_decay: 0.1
  warm_up_steps: 500
  initial_lr: 1.0e-20
  final_lr: 1.0e-10
seed: 0
log_freq: 10
eval_freq: 100
no_eval: false
ckpt_freq: 500
save_adapters: true

# wandb:
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false
#   project: embed_llm
#   run_name: 128_SL_FN_Truemean_0_MLP_8_TRUNC_True_CA_16_CAL_False_SKV_False_DB_new_pooled_cross_att
