model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/
exp_name: test_ft


continuation: 0.0
textual_continuation: 0.0

lora_llm:
  enable: false
  rank: 128
  scaling: 2.0

lora_embedder:
  enable: false
  rank: 128
  scaling: 2.0

model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
no_eval: false
num_microbatches: 1

optim:
  final_lr: 1.0e-10
  initial_lr: 1.0e-20
  max_lr: 1.0e-05
  warm_up_steps: 500
  weight_decay: 0.1
pipeline:
  embedder_params:
    causal_embedder: true
    compress_rates:
    - -4
    n_truncated_layers: 16
    pooling_module:
      pool_type: mean_sa
      where: before
    trained_layers: 4
    rec_tok: true
    cont_tok: true
  max_embeds: 1
  trainable_llm: false
  w_embeds: true
  w_prefix_prompt: false
  decoder_module:
    do: true
    n_layers: 1
    insert_at: 16
from_ckpt:
  do: true
  decoder_path: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/SA_merge_L4_CR4_decL16_pt_5rec_conttok/checkpoints/checkpoint_010000/llm/decoder/
  embedder_path: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/SA_merge_L4_CR4_decL16_pt_5rec_conttok/checkpoints/checkpoint_010000/embedder/

data:
  adapt_seq_len: true
  eval_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/eval_ReadComp/squad_test.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/instruct_data/Reading_Comp/squad_v2_only_answered.jsonl:0.5,/lustre/scwpod02/client/kyutai-interns/hippop/processed_data/synthesized/filtered/translation/dan_fr_esp_de_synth_filtered.jsonl:0.5
  few_shot: 5


seq_len: 1024
batch_size: 4
num_microbatches: 1
max_steps: 1000


seed: 0
log_freq: 1
eval_freq: 50
no_eval: false
ckpt_freq: 30

# SQUAD: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/instruct_data/Reading_Comp/squad_v2_only_answered.jsonl
# NQ, TRIVIAQA: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/instruct_data/QA_w_retrieved_passages_NVEmbed/  nq_open_data.jsonl, triviaqa_data.jsonl



