model_id_or_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
llm_name: Mistral7B
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/
exp_name: test_pretrain
# continuation: 1.0
# textual_continuation: 0.0

continuation: 0.5
toy_tests:
  do: true
  kl_pretraining: true
  alpha: 2
  temp: 0.8
  

lora:
  enable: true
  rank: 64
  scaling: 2.0

  
pipeline:
  cross_att: true
  cross_att_layers: 16
  do_both: true
  do_pool: true
  embedder_name: Mistral7B
  every_cross_att: null
  gate_bottleneck: 8
  mlp_project:
    act: gelu
    hidden_dim: 4096
    n_layers: 1
    type: mlp
  n_truncated_layers: 8
  pooled_cross_att: false
  max_embeds: 3
  pooling_module:
    n_heads: 8
    r: 512
    type: latent_attention
  shared_kv: false
  train_only_pooling: false
  trainable_embedder: true
  trainable_llm: false
  w_embeds: true

data:
  adapt_seq_len: false
  eval_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/crawl/eval_en_00_of_18.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/crawl_2/train_en_00_of_18.jsonl

seq_len: 256
batch_size: 32
num_microbatches: 1
max_steps: 40000
optim:
  max_lr: 5.0e-05
  weight_decay: 0.1
  warm_up_steps: 500
  initial_lr: 1.0e-20
  final_lr: 1.0e-10

seed: 0
log_freq: 1
eval_freq: 1
no_eval: true
ckpt_freq: 1
save_adapters: true


# wandb:
#   project: embed_llm
#   run_name: pretrain_both_trained_07_singpassage_0f6f2a1a
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false




