
# Models
model_id_or_path : /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B
llm_name: Mistral7B
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/
exp_name: Mistral_concat
norm_wo_embeds: False
lora:
  rank: 64
  scaling : 2.0
  enable: True

# Projector 
projector:
  hidden_dim: 768
  n_layers: 3
  act: id
  

# Embedder
embedder:
  dim: 4096
  name: 'NVEmbed'
  

# Data
data:
  train_data: /lustre/scwpod02/client/kyutai-interns/datasets/modular_finetuning/enwiki-20220120_train.jsonl
  eval_data: /lustre/scwpod02/client/kyutai-interns/datasets/modular_finetuning/enwiki-20220120_valid.jsonl
  shuffle: False


# Training and Optim
seq_len: 512
batch_size: 1
max_steps: 100000
optim:
  lr: 6.e-5
  weight_decay: 0.1
  pct_start: 0.05


# other
seed: 0
log_freq: 1
eval_freq: 4
no_eval: False
ckpt_freq: 2
save_adapters: False # save only trained LoRA adapters. Set to `False` to merge LoRA adapter into the base model and save full fine-tuned model


# Monitoring
# wandb: 
#   project: embed_llm  # your wandb project name
#   run_name: Mistral_concat  # your wandb run name
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706 # your wandb api key
#   offline: True
    

