# Llama3.1-8B  Llama3.2-3B
# Llama3.1-8B  Llama3.2-3B
embedder_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/Llama3.2-3B

llm_paths: 
  - /lustre/scwpod02/client/kyutai-interns/hippop/models/Llama3.1-8B
  - /lustre/scwpod02/client/kyutai-interns/hippop/models/mistral_7B

llm_types: 
  - llama
  - mistral

embed_type: llama

run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/

exp_name: multi_decoder_nodist_CP8_ft
continuation: 0.0
num_microbatches: 1
seed: 0
max_steps: 2000
seq_len: 1024
log_freq: 10
batch_size: 16
ckpt_freq: 100
eval_freq: 50
no_eval: false
optim:
  final_lr: 1.0e-10
  initial_lr: 1.0e-20
  max_lr: 1.0e-06
  max_lr_projector: 1.0e-05
  warm_up_steps: 50
  weight_decay: 0.1

pipeline:
  embedder_params:
    causal_embedder: true
    compress_rates:
    - -8
    n_truncated_layers: 14
    pooling_module:
      pool_type: mean_sa
      where: before
    trained_layers: 14
    rec_tok: true
    cont_tok: true
    train_embedding_mtx: true
  max_embeds: 1
  trainable_llm: false
  w_embeds: true
  w_prefix_prompt: false
  bridge_module:
    bridge_type: multi_module
    in_dim: 3072
    hidden_dim: 2048
    out_dim: 4096

from_ckpt:
  do: true
  embedder_path: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/multi_decoder_nodist_CP8/checkpoints/checkpoint_030000/embedder/
  bridge_path: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/multi_decoder_nodist_CP8/checkpoints/checkpoint_030000/bridge_module/


data:
  adapt_seq_len: true
  eval_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/eval_ReadComp/squad_test.jsonl
  shuffle: false
  train_data: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/instruct_data/Reading_Comp/squad_v2_only_answered.jsonl


wandb:
  project: embed_llm
  run_name: multi_decoder_nodist_CP8_ft
  key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
  offline: false




