data:
  eval_data: ''
  prefix_path: /lustre/scwpod02/client/kyutai-interns/hippop/processed_data/synthesized/long_context/
  train_data: summ_atlas_gemma-3-27b-itgemma-3-27b-it_v2_formatted.jsonl:8:0,summ_arxiv_gemma-3-27b-itgemma-3-27b-it_v2_formatted.jsonl:5:0,qa_atlas_gemma-3-27b-itgemma-3-27b-it_v2_formatted.jsonl:10:0,qa_arxiv_gemma-3-27b-itgemma-3-27b-it_v2_formatted.jsonl:5:0,qa_books_gemma-3-27b-itgemma-3-27b-it_v2_formatted.jsonl:10:0,summ_books_gemma-3-27b-itgemma-3-27b-it_v2_formatted.jsonl:8:0,summ_long_qm_arxiv_gemma-3-27b-itgemma-3-27b-it_long_formatted.jsonl:8.0:0,summ_long_qm_books_gemma-3-27b-itgemma-3-27b-it_long_formatted.jsonl:10:0
  interleave: true
  chunk_to: 1024
  max_chunks: 31
  instruct_decoder: true
  instruct: true
  
  
run_dir: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/
llm_paths:  
  - /lustre/scwpod02/client/kyutai-interns/hippop/models/Llama2-7B-Chat
llm_types: 
  - llama_2
embedder_path: /lustre/scwpod02/client/kyutai-interns/hippop/models/Llama3.2-3B
embed_type: llama
num_microbatches: 4
seed: 0
max_steps: 8000
seq_len: 1024
log_freq: 10
batch_size: 2
ckpt_freq: 500
eval_freq: 50
no_eval: true
continuation: 0.0
optim:
  final_lr: 1.0e-8
  initial_lr: 1.0e-20
  max_lr: 2.0e-06
  max_lr_projector: 3.0e-05
  warm_up_steps: 1000
  weight_decay: 0.05
pipeline:
  embedder_params:
    causal_embedder: false
    compress_rates:
    - -8
    n_truncated_layers: 2
    pooling_module:
      pool_type: mean_pooled_queries
      where: before
    trained_layers: 27
    train_embedding_mtx: true
    rec_tok: False
    cont_tok: False
  bridge_module:
    bridge_type: mlp
    in_dim: 3072
    hidden_dim: 2048
    out_dim: 4096
from_ckpt:
  do: true
  bridge_path: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/Instruct_CP8_long_pt/checkpoints/checkpoint_080000/bridge_module/
  embedder_path: /lustre/scwpod02/client/kyutai-interns/hippop/tmp/hp_v2/Instruct_CP8_long_pt/checkpoints/checkpoint_080000/embedder/
num_ckpt_keep: 2
exp_name: instruct_test
# wandb:
#   key: 79d15dbc90cdc10b0d5e5ad252ae8ddbef9fd706
#   offline: false
#   project: embed_llm
#   run_name: Instruct_CP8_long_pt
